#!/bin/bash
echo Compilando ...
javac -cp bin src/toolkit/Randomizer.java -d bin
javac -cp bin src/toolkit/StringUtil.java -d bin
javac -cp bin src/toolkit/IntUtil.java -d bin
javac -cp bin src/toolkit/Main.java -d bin
echo Compilado.